# Site settings
title: Fin Addicts
email: FinAddictsFishingTeam@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  This is the site of the Fin Fishing team.
baseurl: "/FinFishingSite" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://nickbristow.github.io/FinFishingSite"
twitter_username: rbristow
github_username:  nickbristow

# Build settings
markdown: kramdown
